In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv("D:\\Course\\Python\\Datasets\\Churn_Modelling.csv")


In [3]:
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [4]:
X = dataset.iloc[:, 3:13].values
X
y = dataset.iloc[:, 13].values
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [5]:
X

test1 = pd.DataFrame(X)
test1

0        1       2   3   4        5  6  7  8        9
0     619   France  Female  42   2        0  1  1  1   101349
1     608    Spain  Female  41   1  83807.9  1  0  1   112543
2     502   France  Female  42   8   159661  3  1  0   113932
3     699   France  Female  39   1        0  2  0  0  93826.6
4     850    Spain  Female  43   2   125511  1  1  1  79084.1
...   ...      ...     ...  ..  ..      ... .. .. ..      ...
9995  771   France    Male  39   5        0  2  1  0  96270.6
9996  516   France    Male  35  10  57369.6  1  1  1   101700
9997  709   France  Female  36   7        0  1  0  1  42085.6
9998  772  Germany    Male  42   3  75075.3  2  1  0  92888.5
9999  792   France  Female  28   4   130143  1  1  0  38190.8

[10000 rows x 10 columns]

In [6]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

# Converting the categorical data into Number (0 ,1 ,2)

labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])

labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])





In [7]:
X
test2 = pd.DataFrame(X)
test2

0  1  2   3   4        5  6  7  8        9
0     619  0  0  42   2        0  1  1  1   101349
1     608  2  0  41   1  83807.9  1  0  1   112543
2     502  0  0  42   8   159661  3  1  0   113932
3     699  0  0  39   1        0  2  0  0  93826.6
4     850  2  0  43   2   125511  1  1  1  79084.1
...   ... .. ..  ..  ..      ... .. .. ..      ...
9995  771  0  1  39   5        0  2  1  0  96270.6
9996  516  0  1  35  10  57369.6  1  1  1   101700
9997  709  0  0  36   7        0  1  0  1  42085.6
9998  772  1  1  42   3  75075.3  2  1  0  92888.5
9999  792  0  0  28   4   130143  1  1  0  38190.8

[10000 rows x 10 columns]

In [ ]:
# Creating 3 dummy varabiles for country ( Factor level of 3 spain , France and Germany)

#onehotencoder = OneHotEncoder()
#X = onehotencoder.fit_transform(X).toarray()
#X = X[:, 1:]


#onehotencoder = OneHotEncoder()
#X = onehotencoder.fit_transform(X).toarray()
#X = X[:, 1:]

In [8]:
from sklearn.compose import ColumnTransformer

ct = ColumnTransformer([("Geography", OneHotEncoder(), [1])], remainder = 'passthrough')

X = ct.fit_transform(X)



C:\Users\rgandyala\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [9]:
abc=pd.DataFrame(X)
abc

0  1  2    3  4   5   6        7  8  9 10       11
0     1  0  0  619  0  42   2        0  1  1  1   101349
1     0  0  1  608  0  41   1  83807.9  1  0  1   112543
2     1  0  0  502  0  42   8   159661  3  1  0   113932
3     1  0  0  699  0  39   1        0  2  0  0  93826.6
4     0  0  1  850  0  43   2   125511  1  1  1  79084.1
...  .. .. ..  ... ..  ..  ..      ... .. .. ..      ...
9995  1  0  0  771  1  39   5        0  2  1  0  96270.6
9996  1  0  0  516  1  35  10  57369.6  1  1  1   101700
9997  1  0  0  709  0  36   7        0  1  0  1  42085.6
9998  0  1  0  772  1  42   3  75075.3  2  1  0  92888.5
9999  1  0  0  792  0  28   4   130143  1  1  0  38190.8

[10000 rows x 12 columns]

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)


In [2]:

from xgboost.sklearn import XGBClassifier

classifier = XGBClassifier()


In [13]:
classifier.fit(X_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=0, num_parallel_tree=1,
              objective='binary:logistic', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [14]:
y_pred = classifier.predict(X_test)

In [15]:
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [16]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [17]:
cm

array([[1541,   69],
       [ 200,  190]], dtype=int64)

In [18]:
from sklearn.metrics import accuracy_score 
Accuracy_Score = accuracy_score(y_test, y_pred)

In [19]:
Accuracy_Score

0.8655