In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv("D:\\Course\\Python\\Datasets\\Position_Salaries.csv")

In [3]:
dataset

Position  Level   Salary
0   Business Analyst      1    45000
1  Junior Consultant      2    50000
2  Senior Consultant      3    60000
3            Manager      4    80000
4    Country Manager      5   110000
5     Region Manager      6   150000
6            Partner      7   200000
7     Senior Partner      8   300000
8            C-level      9   500000
9                CEO     10  1000000

In [4]:
X = dataset.iloc[:, 1:2].values

In [5]:
X = dataset.iloc[:, 1:2].values
y

array([[  45000],
       [  50000],
       [  60000],
       [  80000],
       [ 110000],
       [ 150000],
       [ 200000],
       [ 300000],
       [ 500000],
       [1000000]], dtype=int64)

In [7]:
# Feature Scaling

In [6]:
from sklearn.preprocessing import StandardScaler

In [7]:
sc_X = StandardScaler()
X = sc_X.fit_transform(X)


In [13]:
sc_y = StandardScaler()
y = sc_y.fit_transform(y)

In [36]:
X

array([[-1.5666989 ],
       [-1.21854359],
       [-0.87038828],
       [-0.52223297],
       [-0.17407766],
       [ 0.17407766],
       [ 0.52223297],
       [ 0.87038828],
       [ 1.21854359],
       [ 1.5666989 ]])

In [14]:
y

array([[-0.72004253],
       [-0.70243757],
       [-0.66722767],
       [-0.59680786],
       [-0.49117815],
       [-0.35033854],
       [-0.17428902],
       [ 0.17781001],
       [ 0.88200808],
       [ 2.64250325]])

# Support Vector Regression Model

In [8]:
# Fitting SVR to the dataset
from sklearn.svm import SVR

In [15]:
regressor = SVR(kernel = 'rbf')
regressor.fit(X, y)

#regre

C:\Users\rgandyala\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1,
    gamma='auto_deprecated', kernel='rbf', max_iter=-1, shrinking=True,
    tol=0.001, verbose=False)

In [21]:
#ypred = regressor.predict([[6.5]])

In [1]:
#ypred

In [18]:
# Predicting a new result
y_pred1 = sc_y.inverse_transform(regressor.predict(sc_X.transform(np.array([[6.5]]))))

In [20]:
y_pred1

array([170370.0204065])

# Decision Tree Regression Model

In [28]:
from sklearn.tree import DecisionTreeRegressor

In [29]:
regressor2 = DecisionTreeRegressor()


In [30]:
regressor2.fit(X, y)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=None, splitter='best')

In [31]:
# Predicting a new result
y_pred2 = sc_y.inverse_transform(regressor2.predict(sc_X.transform(np.array([[6.5]]))))

In [32]:
y_pred2

array([200000.])

# Random Forest Regression

In [33]:
from sklearn.ensemble import RandomForestRegressor
regressor3 = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor3.fit(X, y)

C:\Users\rgandyala\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=10,
                      n_jobs=None, oob_score=False, random_state=0, verbose=0,
                      warm_start=False)

In [34]:
y_pred3 = sc_y.inverse_transform(regressor.predict(sc_X.transform(np.array([[6.5]]))))

In [35]:
y_pred3

array([210000.])